#!/usr/bin/env python
"""track4_certify.py — Track-4 quick wins: G4 certificate ladder + polyform
counts for two KNOWN space-filling cells that have no OEIS polyform sequences:

  A  LAVES-17  the Laves-graph (srs net) plesiohedron: Voronoi cell of Wyckoff
               8a of I4_132 (IT 214), generating point (1/8, 1/8, 1/8).
               Literature: 17 faces (Wikipedia "Laves graph"; Schmitt 2016
               IT(214) table row (30,45,17) at (1/8,1/8,1/8), printed p. 136).
  B  ENGEL-38  Engel's 38-facet stereohedron (the record cell): Schmitt 2016
               IT(214) table row (70,106,38), printed representative point
               (427/6984, 761/6984, 1421/6984), printed p. 138 (PDF p. 143),
               visually confirmed + text layer.  IT(214) is single-origin.

NOTHING HERE CLAIMS NOVELTY OF EITHER CELL: both are established literature
objects.  Only the polyform SEQUENCES are new.

Pipeline (house invariant: floats propose, Fractions decide):
  V0  orbit (frozen G1 spacegroups.json) -> float sweep -> exact clip ->
      canonical code; facet count asserted against the literature value
      (17 / 38) — a mismatch STOPS the run (never forced).  For LAVES the
      canonical code is also asserted equal to the Phase-1 store type
      8c69db9e84095469 (already sighted there at IT(214) (1/8,1/8,1/8)).
  V1-V3  verbatim g4_certify.py stages (imported, not copied): tiling
      certificate + independent adapted audit, symmetry over ALL orthogonal
      maps + Bravais point group of the actual lattice, tables + banked
      enumerator n<=N_ENUM + banked burnside_generic.py identity.
  Then counts: banked export_tables.py + compiled enumerate (full ops ->
      fixed/free; proper ops -> one-sided), per-run cap CAP_S, n=6 -> 5 -> 4
      fallback (recorded, never silent).

Run:  python3 track4_certify.py [laves|engel ...]
Writes (in track4/): g4_tables_<key>.json/.txt/_proper.txt, track4_results.json,
TRACK4_CERT_LOG.md.  Exit 0 iff every V-stage of every requested cell is PASS.
"""
import json
import os
import subprocess
import sys
import time
import traceback
from fractions import Fraction as F

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(HERE)
HARNESS = os.path.join(PROJ, "harness")
sys.path.insert(0, HARNESS)

import orbit                                    # noqa: E402
from sweep_voronoi import sweep                 # noqa: E402
from exact_cell import clip_cell                # noqa: E402
from canon_code import canonical_code           # noqa: E402
from sweep_phase1 import wyckoff_dim            # noqa: E402
import g4_certify as G4                          # noqa: E402
from g4_certify import pvec_compact             # noqa: E402

# g4_certify writes its tables next to its own HERE; redirect to track4/.
G4.HERE = HERE
# The V3 soft budget is measured from the candidate's start; the Engel cell's
# V1 audit alone (70 vertices x 24 reps, period-6984 Fractions) exceeds the
# harness default.  Enumerator caps are handled per run below (CAP_S).
G4.BUDGET_S = 6 * 3600


def derive_lattice_cosets(base, P):
    """Primitive translation lattice of the periodic set base mod P — same
    contract as mint_tables.derive_lattice (returns (B columns int, detL>0)),
    but COMPLETE by a coset argument instead of a P^3 grid scan (the original
    enumerates range(-P,P+1)^3, infeasible for the Engel cell's P = 6984):
    any translation t with S + t = S maps base[0] to some site, so
    t == base[j] - base[0] (mod P Z^3) for some j.  Hence L is generated by
    P e_i together with those of the n deltas d_j = base[j]-base[0] (mod P)
    that preserve S mod P.  A triple of generators spans L iff it integrally
    spans every generator; a spanning triple has |det| = covol(L)."""
    from itertools import combinations
    from mint_tables import det3, mat_inv, mat_vec, to_int_mat
    baseset = set((x % P, y % P, z % P) for x, y, z in base)
    b0 = base[0]
    gens = [(P, 0, 0), (0, P, 0), (0, 0, P)]
    for q in base:
        d = tuple((q[i] - b0[i]) % P for i in range(3))
        if d == (0, 0, 0):
            continue
        if set(((x+d[0]) % P, (y+d[1]) % P, (z+d[2]) % P)
               for x, y, z in base) == baseset:
            # symmetric representative (shortest coset member) for the search
            gens.append(tuple(c - P if c > P // 2 else c for c in d))
    short = sorted(set(gens), key=lambda t: (sum(x*x for x in t), t))[:20]
    for a, b, c in combinations(short, 3):
        dd = det3(a, b, c)
        if dd == 0:
            continue
        Bcols = [[F(a[i]), F(b[i]), F(c[i])] for i in range(3)]
        Binv = mat_inv(Bcols)
        if all(all(F(x).denominator == 1 for x in mat_vec(Binv, t))
               for t in gens):
            return to_int_mat(Bcols), abs(dd)
    raise AssertionError("no primitive basis found among shortest translations")


# Self-check on a feasible period: coset version == original grid version.
def _selfcheck_lattice(pts, P):
    from mint_tables import derive_lattice as _orig
    B1, d1 = derive_lattice_cosets(pts, P)
    B2, d2 = _orig(pts, P)
    assert d1 == d2, "coset lattice derivation disagrees with grid version (det)"
    # same lattice: each basis integrally expresses the other
    from mint_tables import mat_inv, mat_vec
    for Ba, Bb in ((B1, B2), (B2, B1)):
        Binv = mat_inv([[F(Ba[i][j]) for j in range(3)] for i in range(3)])
        for j in range(3):
            v = tuple(Bb[i][j] for i in range(3))
            assert all(F(x).denominator == 1 for x in mat_vec(Binv, v)), \
                "coset lattice != grid lattice"
    return d1


G4.derive_lattice = derive_lattice_cosets

PYTHON = G4.PYTHON
EXPORT_TABLES = G4.EXPORT_TABLES
ENUM_BIN = G4.ENUM_BIN
STORE = os.path.join(HARNESS, "phase1_types.json")

CAP_S = 20 * 60          # per enumerator run cap (tasking: 20 min per n)

CELLS = {
    "laves": dict(
        key="laves", cid="laves17",
        name="Laves graph plesiohedron",
        group=214, point=("1/8", "1/8", "1/8"),
        lit_facets=17, lit_f=(30, 45, 17),
        store_type="8c69db9e84095469",
        n_enum=4, want_n=6,
        lit=("Wikipedia 'Laves graph' (symmetry I4_132; Voronoi cells are "
             "congruent 17-sided plesiohedra); Schmitt 2016 IT(214) table, "
             "row (30,45,17) at (1/8,1/8,1/8), printed p. 136")),
    "engel": dict(
        key="engel", cid="engel38",
        name="Engel's 38-facet stereohedron",
        group=214, point=("427/6984", "761/6984", "1421/6984"),
        lit_facets=38, lit_f=(70, 106, 38),
        store_type=None,
        n_enum=4, want_n=6,     # n=6 timed at ~205 s per run (2026-09-03), under CAP_S
        lit=("Engel 1981 (Z. Krist. 154, 199-215) via Schmitt 2016 sec. 2.3 "
             "(four 38-facet types confirmed, no fifth); printed "
             "representative point from Schmitt's IT(214) table, row "
             "(70,106,38), printed p. 138 / PDF p. 143, frequency 153")),
}


def v0_track4(spec, groups, store):
    """Literature-anchored V0: derive, assert facet count == literature."""
    g = groups[spec["group"]]
    p = tuple(F(s) for s in spec["point"])
    ob = orbit.orbit(g, p)
    pts, period = orbit.scale_orbit(ob["points"])
    try:
        cells_f, W = sweep(pts, period, W=2), 2
    except RuntimeError:
        cells_f, W = sweep(pts, period, W=3), 3
    ec = clip_cell(pts[0], pts, period)
    assert 4 * ec["rho2"] <= ec["cutoff_D"] ** 2, "cutoff certificate violated"
    Fc = ec["facet_count"]
    V = ec["n_vertices"]
    E = sum(len(c) for c in ec["facet_cycles"]) // 2
    assert V - E + Fc == 2, "Euler failure"
    assert Fc <= G4.MAX_FACETS, f"KILL: {Fc} > {G4.MAX_FACETS} facets"
    # THE literature check — never forced
    assert Fc == spec["lit_facets"], \
        f"STOP: facet count {Fc} != literature {spec['lit_facets']}"
    assert (V, E, Fc) == spec["lit_f"], \
        f"STOP: f-vector {(V, E, Fc)} != literature {spec['lit_f']}"
    f0 = cells_f[0]
    nbr_f = {tuple(pts[0][k] + d[k] for k in range(3))
             for d in f0["neighbor_deltas"]}
    agree = (f0["facet_count"] == Fc and f0["p_vector"] == ec["p_vector"]
             and nbr_f == set(ec["neighbors"]))
    assert agree or f0["degenerate_flag"], "float/exact disagree, unflagged"
    code, aut = canonical_code(ec["facet_cycles"])
    code_s = code.decode("ascii")
    store_note = "not in Phase-1 store (general position, T=24)"
    if spec["store_type"]:
        ent = store[spec["store_type"]]
        assert code_s == ent["canon_code"], "canonical code != stored type"
        assert list(ent["f_vector"]) == [V, E, Fc]
        assert aut == ent["aut_order"]
        store_note = f"canonical code == store type {spec['store_type']}"
    site_ops = orbit.site_stabilizer(g, p)
    ctx = {
        "cid": spec["cid"], "g": g, "p": p, "ob": ob, "pts": pts,
        "period": period, "ec": ec, "code": code_s, "aut": aut,
        "Fc": Fc, "V": V, "E": E, "site_ops": site_ops, "W": W,
        "float_agree": agree, "degenerate_flag": f0["degenerate_flag"],
        "stratum_dim": wyckoff_dim(g, p),
        "detail": (f"IT({spec['group']}) {g['international_short']} "
                   f"p=({', '.join(spec['point'])}) period={period} "
                   f"n_conv={ob['n_conventional']} T={ob['n_primitive']} "
                   f"stab={ob['stabilizer_order']} "
                   f"stratum_dim={wyckoff_dim(g, p)} f=({V},{E},{Fc}) "
                   f"p-vec {pvec_compact(ec['p_vector'])} aut={aut} "
                   f"nonsimple={ec['nonsimple_vertices']} W={W} "
                   f"float{'==' if agree else '!='}exact"
                   f"{' (degenerate-flagged, exact decides)' if f0['degenerate_flag'] else ''} "
                   f"cutoff_D={ec['cutoff_D']} 4rho2={4*ec['rho2']}; "
                   f"FACETS {Fc} == literature {spec['lit_facets']}; {store_note}"),
    }
    return ctx


def run_enum(txt, n, timeout):
    r = subprocess.run([ENUM_BIN, txt, str(n)], check=True,
                       capture_output=True, text=True, timeout=timeout)
    counts, hdr = {}, False
    for line in r.stdout.splitlines():
        if line.strip() == "n fixed free":
            hdr = True
            continue
        if hdr and line.split():
            nn, fx, fr = line.split()
            counts[int(nn)] = (int(fx), int(fr))
    assert len(counts) == n
    return counts


def enum_capped(txt, want_n):
    """Each n gets its own CAP_S; fall back n-1 on timeout (recorded)."""
    notes = []
    for n in range(want_n, 3, -1):
        t0 = time.time()
        try:
            c = run_enum(txt, n, CAP_S)
            notes.append(f"n<={n} completed in {time.time()-t0:.0f}s")
            return c, n, "; ".join(notes)
        except subprocess.TimeoutExpired:
            notes.append(f"n<={n} TIMEOUT at {CAP_S}s")
    return None, 0, "; ".join(notes)


def certify(spec, groups, store, say):
    t_c0 = time.time()
    G4.N_ENUM = spec["n_enum"]
    deadline = t_c0 + G4.BUDGET_S
    stages = []
    out = {"key": spec["key"], "name": spec["name"], "stages": stages}

    def stage(name, fn):
        t0 = time.time()
        try:
            res = fn()
            dt = time.time() - t0
            verdict = "DEFERRED" if isinstance(res, dict) and res.get("deferred") \
                else "PASS"
            detail = res["detail"] if isinstance(res, dict) and "detail" in res \
                else res if isinstance(res, str) else ""
            stages.append({"name": name, "verdict": verdict, "detail": detail,
                           "t": round(dt, 1)})
            say(f"  {name}: {verdict} ({dt:.1f}s) {detail[:140]}")
            return res
        except Exception:
            dt = time.time() - t0
            tb = traceback.format_exc().strip().splitlines()[-1]
            stages.append({"name": name, "verdict": "FAIL", "detail": tb,
                           "t": round(dt, 1)})
            say(f"  {name}: FAIL ({dt:.1f}s) {tb}")
            raise

    say(f"[{spec['key']}] {spec['name']} — literature facets "
        f"{spec['lit_facets']}, IT({spec['group']}) p=({', '.join(spec['point'])})")
    ctx = lat = sym = v3 = None
    try:
        ctx = stage("V0 exact derivation vs literature",
                    lambda: v0_track4(spec, groups, store))
        cl = stage("V1 tiling certificate (generator)",
                   lambda: dict(zip(("cert", "lat", "detail"),
                                    G4.v1_generate(ctx))))
        cert, lat = cl["cert"], cl["lat"]
        stage("V1 independent adapted audit",
              lambda: G4.v1_audit(json.loads(json.dumps(cert))))
        sym = stage("V2 symmetry certification",
                    lambda: G4.v2_symmetry(ctx, lat))
        v3 = stage("V3 Burnside identity",
                   lambda: G4.v3_tables_burnside(ctx, lat, sym, deadline))
    except Exception:
        pass
    out["elapsed_cert"] = round(time.time() - t_c0, 1)
    if ctx is not None:
        out.update(f_vector=[ctx["V"], ctx["E"], ctx["Fc"]],
                   p_vector=pvec_compact(ctx["ec"]["p_vector"]),
                   aut=ctx["aut"], period=ctx["period"],
                   n_conv=ctx["ob"]["n_conventional"], T=ctx["ob"]["n_primitive"],
                   stabilizer=ctx["ob"]["stabilizer_order"],
                   stratum_dim=ctx["stratum_dim"],
                   nonsimple=ctx["ec"]["nonsimple_vertices"],
                   canon_code=ctx["code"],
                   rho2=str(ctx["ec"]["rho2"]),
                   vertices=[[str(x) for x in v] for v in ctx["ec"]["vertices"]],
                   facet_cycles=ctx["ec"]["facet_cycles"],
                   neighbors=[list(q) for q in ctx["ec"]["neighbors"]],
                   scaled_orbit=[list(q) for q in ctx["pts"]],
                   cell_volume=str(G4.cell_volume_from_cycles(ctx["ec"])))
    if sym is not None:
        out.update(n_site=sym["n_site"], n_geo=sym["n_geo"], n_brav=sym["n_brav"],
                   all_sp_brav=sym["all_sp_brav"], all_sp_stab=sym["all_sp_stab"])
    if lat is not None:
        out.update(detL=lat["detL"],
                   lattice_basis=[[lat["Bcols"][i][j] for i in range(3)]
                                  for j in range(3)])
    if v3 is not None and not v3.get("deferred"):
        out.update(g4_counts={str(n): list(v) for n, v in v3["counts"].items()},
                   n_ops=v3["n_ops"], n_proper=v3["n_proper"])

    # ---- counts (banked workflow), only if the ladder fully passed
    allpass = all(s["verdict"] == "PASS" for s in stages) and len(stages) == 5
    out["ladder_allpass"] = allpass
    if allpass:
        tables_json = os.path.join(HERE, f"g4_tables_{spec['cid']}.json")
        full_txt = os.path.join(HERE, f"g4_tables_{spec['cid']}.txt")
        prop_txt = os.path.join(HERE, f"g4_tables_{spec['cid']}_proper.txt")
        subprocess.run([PYTHON, EXPORT_TABLES, tables_json, prop_txt,
                        "proper_ops"], check=True, capture_output=True)
        say("  counts: full-ops enumerate ...")
        cf, nf, notef = enum_capped(full_txt, spec["want_n"])
        say(f"    full: n<={nf} ({notef})")
        say("  counts: proper-ops enumerate ...")
        cp, np_, notep = enum_capped(prop_txt, spec["want_n"])
        say(f"    proper: n<={np_} ({notep})")
        assert cf is not None and cp is not None
        for n in range(1, G4.N_ENUM + 1):
            assert cf[n] == tuple(v3["counts"][n]), "prefix != V3 counts"
        for n in range(1, min(nf, np_) + 1):
            assert cp[n][0] == cf[n][0], "fixed columns differ"
            assert cf[n][0] >= cp[n][1] >= cf[n][1] > 0
            assert cp[n][1] <= 2 * cf[n][1]
        out.update(counts_fixed=[cf[n][0] for n in range(1, nf + 1)],
                   counts_free=[cf[n][1] for n in range(1, nf + 1)],
                   counts_onesided=[cp[n][1] for n in range(1, np_ + 1)],
                   nmax_full=nf, nmax_proper=np_, note_full=notef,
                   note_proper=notep)
        say(f"  fixed {out['counts_fixed']}\n  free {out['counts_free']}\n"
            f"  one-sided {out['counts_onesided']}")
    out["elapsed_total"] = round(time.time() - t_c0, 1)
    return out


def main(argv):
    keys = argv[1:] or ["laves", "engel"]
    groups = orbit.load_groups()
    store = json.load(open(STORE))["types"]
    results = []
    t0 = time.time()
    for k in keys:
        results.append(certify(CELLS[k], groups, store, print))
    res_path = os.path.join(HERE, "track4_results.json")
    prev = {}
    if os.path.exists(res_path):
        prev = json.load(open(res_path))
    for r in results:
        prev[r["key"]] = r
    json.dump(prev, open(res_path, "w"), indent=1)
    ok = all(r["ladder_allpass"] for r in results)
    # the log covers EVERY cell in the merged results store (a per-cell run
    # must not erase the other cell's banked entry); this run's cells are marked
    L = [f"# Track-4 certificate log — {time.strftime('%Y-%m-%d')}", "",
         f"Cells re-run in this invocation: {', '.join(keys)}; other entries "
         "are reproduced from track4_results.json (their own earlier run).", ""]
    for r in [prev[k] for k in sorted(prev)]:
        L.append(f"## {r['name']} (`{r['key']}`)")
        L.append("")
        L.append("| stage | verdict | wall | detail |")
        L.append("|---|---|---|---|")
        for s in r["stages"]:
            L.append(f"| {s['name']} | **{s['verdict']}** | {s['t']}s | {s['detail']} |")
        L.append("")
    L.append(f"Total wall {time.time()-t0:.0f}s. Verdict: "
             f"{'ALL LADDERS PASS' if ok else 'FAIL/DEFERRED'}.")
    open(os.path.join(HERE, "TRACK4_CERT_LOG.md"), "w").write("\n".join(L) + "\n")
    print(f"\nTRACK4 VERDICT: {'ALL LADDERS PASS' if ok else 'FAIL/DEFERRED'} "
          f"({time.time()-t0:.0f}s)")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
